stages:
- stage: ci
  jobs:
  - job: Build
    steps:
    - task: Maven@4
      displayName: Maven Build
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        goals: 'clean package'
        options: '-B'
        javaHomeOption: 'Path'
        jdkDirectory: $(SYSTEM_JDK_17)
        mavenVersionOption: 'Path'
        mavenDirectory: $(SYSTEM_MAVEN_3_HOME)

    # Creating artifacts that contains only the JAR file.
    # Change the JAR file name as per your application artifact name.
    - bash: mkdir artifacts ; cp target/pasta-bishop-*.jar artifacts/
      displayName: Prepare Artifacts

    # Publish the artifacts so that the deploy stage can consume it. 
    - publish: artifacts
      artifact: drop
      displayName: Publish Artifact

  - job: Security Scan
    variables: 
    - group: SDLC Credentials
    steps:
    - task: Maven@4
      displayName: Plugin
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install com.sonatype.clm:clm-maven-plugin:index -Dclm.additionalScopes=provided'
        options: '-B -e -Dno-docker -DskipTests'
        javaHomeOption: 'Path'
        jdkDirectory: $(SYSTEM_JDK_17)
        mavenVersionOption: 'Path'
        mavenDirectory: $(SYSTEM_MAVEN_3_HOME)

    - template: lifecycle-scan.yml@sdlc_templates
      parameters:
        IQ_API_TOKEN: $(IQ_API_TOKEN)
        ARTIFACT_VERSION: "$(Build.BuildId)"
        DISTRIBUTION: Hosted
        ENABLE_CALLFLOW: true

  - job: checkmarx_scan
    displayName: Checkmarx Scan
    variables:
      - group: 'SDLC Credentials'
    steps:
      - template: checkmarx-scan.yml@sdlc_templates
        parameters:
          CHECKMARX_PASSWORD: "$(CHECKMARX_PASSWORD)"
          PROJECT_NAME: "sandbox-maven-dtr-ucp"
          PROJECT_VERSION: $(Build.BuildId)
          TEAM: "sandbox"
          # CHECKMARX_ARGUMENTS is optional.  Add it if you want to skip any files.
          CHECKMARX_ARGUMENTS: -LocationPathExclude "grails-app/assets/javascripts,src/test,src/integration-test,grails-app/taglib/twitter/bootstrap" -LocationFilesExclude "**/grails-wrapper.jar"

