parameters:
- name: stage_name
- name: ado_environment
- name: az_service_connection_sc
- name: variable_group
- name: depends_on
  type: object
  default: ['ci']
- name: condition
  default: succeeded()

stages:
- stage: ${{ parameters.stage_name }}
  dependsOn: ${{ parameters.depends_on }}
  condition: ${{ parameters.condition }}
  jobs:
  - deployment: DacPac_Deploy
    environment: ${{ parameters.ado_environment }}
    variables:
    - group: ${{ parameters.variable_group }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: SqlAzureDacpacDeployment@1
            inputs:
              azureSubscription: ${{ parameters.az_service_connection_sc }}
              AuthenticationType: 'servicePrincipal'
              ServerName: '$(var_db_host)'
              DatabaseName: '$(var_db_name)'
              deployType: 'DacpacTask'
              DeploymentAction: 'Publish'
              DacpacFile: '$(Pipeline.workspace)/drop-$(Build.BuildId)/dacpac_poc.dacpac'
              IpDetectionMethod: 'AutoDetect'
