parameters:
  - name: ado_environment
  - name: deploy_variable_group
  - name: stage_name
  - name: az_subscription_sc
  - name: depends_on
    type: object
    default: ['ci']
  - name: condition
    default: succeeded()

stages:
  - stage: ${{ parameters.stage_name }}
    dependsOn: ${{ parameters.depends_on }}
    condition: ${{ parameters.condition }}

    variables:
      - group: "${{ parameters.deploy_variable_group }}"

    jobs:
      - template: update-ca.yaml
        parameters:
          job_name: retrive_ca
          ado_environment: "${{ parameters.ado_environment }}"
          variable_group: "${{ parameters.deploy_variable_group }}"
          app_service_slot: $(APP_SERVICE_SLOT)
          az_subscription_sc: ${{ parameters.az_subscription_sc }}

      - deployment: deploy
        environment: "${{ parameters.ado_environment }}"
        dependsOn: ['update_ca']     
        variables:
          APP_SERVICE_SLOT: 'production'

        strategy:
          runOnce:
            deploy:
              steps:

                - task: AzureCLI@2
                  displayName: Retrieve App Insights Details
                  name: app_insights
                  inputs:
                    azureSubscription: ${{ parameters.az_subscription_sc }}
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      app_insights_instrumentation_key=$(az resource show --resource-type "microsoft.insights/components" --query properties.InstrumentationKey -g $(var_az_app_service_rg) -n $(var_app_insights))
                      app_insights_connection_string=$(az resource show --resource-type "microsoft.insights/components" --query properties.ConnectionString -g $(var_app_insights_rg) -n $(var_app_insights))
                      echo "##vso[task.setvariable variable=APP_INSIGHTS_INSTRUMENTATION_KEY;isOutput=true]$app_insights_instrumentation_key"
                      echo "##vso[task.setvariable variable=APP_INSIGHTS_CONNECTION_STRING;isOutput=true]$app_insights_connection_string"

                # Stopping the app service before upgrading
                - task: AzureAppServiceManage@0
                  displayName: Stop the App Service
                  inputs:
                    azureSubscription:  ${{ parameters.az_subscription_sc }}
                    ResourceGroupName: $(var_az_app_service_rg)
                    WebAppName: $(var_az_app_service)
                    Action: 'Stop Azure App Service'
                    SpecifySlotOrASE: true
                    Slot: '$(APP_SERVICE_SLOT)'

                - task: AzureAppServiceSettings@1
                  displayName: Updating App Settings
                  inputs:
                    azureSubscription: ${{ parameters.az_subscription_sc }}
                    appName: $(var_az_app_service)
                    resourceGroupName: $(var_az_app_service_rg)
                    slotName: '$(APP_SERVICE_SLOT)'
                    appSettings: |
                      [
                        {
                          "name": "SPRING_PROFILES_ACTIVE",
                          "value": "$(var_spring_profiles_active)"
                        },
                        {
                          "name": "PORT",
                          "value": "8080"
                        },
                        {
                          "name": "JAVA_OPTS",
                          "value": "-Xms512m -Xmx2048m"
                        }
                      ]
                    # This is mandatory to set the Azure App Service Stack.
                    generalSettings: |
                      [
                        {
                          "linuxFxVersion": "JAVA|17-java17",
                          "healthCheckPath": "/actuator/health"
                        }
                      ]

                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: ${{ parameters.az_subscription_sc }}
                    ResourceGroupName: $(var_az_app_service_rg)
                    WebAppName: $(var_az_app_service)
                    appType: 'webAppLinux'
                    deployToSlotOrASE: true
                    SlotName: '$(APP_SERVICE_SLOT)'
                    Package: $(Pipeline.Workspace)/drop-$(Build.BuildId)/*.jar
                    RuntimeStack: "JAVA|17-java17"
                    # we are having app insights related settings alone here as the $(app_insights.var) is not working in previous task properly.
                    AppSettings: >
                      -APPINSIGHTS_INSTRUMENTATIONKEY $(app_insights.APP_INSIGHTS_INSTRUMENTATION_KEY)
                      -APPLICATIONINSIGHTS_CONNECTION_STRING $(app_insights.APP_INSIGHTS_CONNECTION_STRING)
                      -ApplicationInsightsAgent_EXTENSION_VERSION ~3

                # Starting the app service.
                - task: AzureAppServiceManage@0
                  displayName: Start the App Service
                  inputs:
                    azureSubscription:  ${{ parameters.az_subscription_sc }}
                    ResourceGroupName: $(var_az_app_service_rg)
                    WebAppName: $(var_az_app_service)
                    Action: 'Start Azure App Service'
                    SpecifySlotOrASE: true
                    Slot: '$(APP_SERVICE_SLOT)'