stages:
- stage: ci
  jobs:
  - job: build
    steps:
    - bash: |
        $PYTHON -m venv antenv
        source ./antenv/bin/activate
        $PYTHON -m pip install -r ./requirements.txt
        rm -rf .git
      displayName: "Install requirements"
      env:
        PYTHON: $(SYSTEM_PYTHON_3_11)

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

  - job: checkmarx_scan
    displayName: Checkmarx Scan
    variables:
      - group: 'SDLC Credentials'
    steps:
      - template: checkmarx-scan.yml@sdlc_templates
        parameters:
          CHECKMARX_PASSWORD: "$(CHECKMARX_PASSWORD)"
          PROJECT_NAME: "sandbox-maven-dtr-ucp"
          PROJECT_VERSION: $(Build.BuildId)
          TEAM: "sandbox"
          # CHECKMARX_ARGUMENTS is optional.  Add it if you want to skip any files.
          CHECKMARX_ARGUMENTS: -LocationPathExclude "grails-app/assets/javascripts,src/test,src/integration-test,grails-app/taglib/twitter/bootstrap" -LocationFilesExclude "**/grails-wrapper.jar"


  - job: NexusLifeCycle_Scan
    steps:
    - template: lifecycle-scan.yml@sdlc_templates
      parameters:
        IQ_API_TOKEN: $(IQ_API_TOKEN)
        ARTIFACT_VERSION: "$(Build.BuildId)"
        DISTRIBUTION: Hosted
