name: Dotnet Linux SonarQube Analysis

on:
  workflow_dispatch: 
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: [self-hosted, premierinc, linux]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Disable shallow clone for better analysis relevance
      
      # Step 2: Set up .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Define the version of .NET SDK
        env:
          DOTNET_INSTALL_DIR: ${{ runner.temp }}/dotnet

      # Step 3: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          overwrite-settings: false  # Prevent overwriting ~/.m2/settings.xml

      # Step 4: Cache SonarQube packages
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache  # Adjust the path for Linux
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Step 5: Cache SonarQube scanner
      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      # Step 6: Install SonarQube scanner if not cached
      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool install dotnet-sonarscanner --tool-path ./.sonar/scanner
          echo "$PWD/.sonar/scanner" >> $GITHUB_PATH

      # Step 7: Run SonarQube Analysis
      - name: SonarQube Analysis
        run: |
          scannerPath="$PWD/.sonar/scanner/dotnet-sonarscanner"
          cd dotnet-project
          $scannerPath begin /k:"code-aakash-test-dotnet" /d:sonar.token="${{ secrets.SYSTEM_SONARQUBE_CE_TOKEN }}" /d:sonar.host.url="${{ vars.SYSTEM_SONARQUBE_CE_URL }}"
          dotnet build
          $scannerPath end /d:sonar.login="${{ secrets.SYSTEM_SONARQUBE_CE_TOKEN }}" /d:sonar.token="${{ secrets.SYSTEM_SONARQUBE_CE_TOKEN }}"