stages:
- stage: ci
  jobs:
  - job: build
    steps:
    - bash: $PYTHON -m pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
      displayName: "Install dependencies"
      env:
        PYTHON: python3.12
  
    - task: ArchiveFiles@2
      displayName: "Archive files"
      inputs:
        rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
        includeRootFolder: false
        archiveFile: "$(System.DefaultWorkingDirectory)/build-$(Build.BuildId).zip"
        
    - publish: "$(System.DefaultWorkingDirectory)/build-$(Build.BuildId).zip"
      artifact: 'drop-$(Build.BuildId)'
