apiVersion: v2
name: nginx-ingress
description: Ingress Controller for AKS Cluster with SSL Certificate

type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: ingress-nginx
    version: 4.12.1
    repository: https://kubernetes.github.io/ingress-nginx
